name: dropdown_button2
description: A custom dropdown button widget for Flutter.
version: 1.9.4

environment:
  sdk: ">=2.12.0 <3.0.0"  # Adjust according to the package's Dart SDK requirements

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  # If there are any other dependencies the package uses, include them here.
